--[[

	ControllerTemplate.luau
	Runtime Controller

	Contributors:
	* Irene "lacelit684" - Lead Developer since 2026-06-27
	State role, add and remove as needed.

	Created: 2026-06-27
	Last Modified: 2026-06-27
	Keep these up to date or your records will suffer your incompetence.
	
	Version: 0.0.0
	Increment the first one when you make a backwards incompatible change to the module.
	Increment the second one when you add backwards compatible functionality.
	Increment the third one when you fix bugs.

	Licence: MPL-2.0

	Description:
	Describe the controller here.
	Keep this short and specific to the module's purpose.

	Dependencies:
	Add any required modules, services, or libraries here.

]]

local Controller = {}

-- Preamble
-- This is where module imports, citations and declarations go.

-- Types
-- This is where types go.

-- Constants
-- This is where constant values go.

-- Variables
-- This is where shared mutable state goes.

-- Functions
-- This is where functions that calculate and return a value go.

-- Procedures
-- This is where functions designed to do something outside of computing and returning a value go.

-- Lifecycle

function ExemplaryService:Init() -- Sets up the state of the controller.

	print("ExemplaryController initialised.")

end

function ExemplaryService:Start() -- Begins the active operation of the controller.

	print("ExemplaryController started.")

end



-- Termination

return Controller