--[[

	DataBlockTemplate.luau
	Data Block

	Contributors:
	* YOUR NAME - YOUR ROLE since YYYY-MM-DD

	Created: YYYY-MM-DD
	Last Modified: YYYY-MM-DD

	Version: 1.2.3
	Increment the first number for breaking changes.
	Increment the second for new backwards-compatible functionality.
	Increment the third for bug fixes.

	Licence: MPL-2.0

	Description:
	Describe the data block here.
	Keep this short and specific to the module's purpose.

	Dependencies:
	Add any required modules, services, or libraries here.

]]

-- Preamble
-- This is where module imports, citations and declarations go.



-- Data
-- This is where data tables and static values go.

local DataBlock = {
	
}



-- Termination

return DataBlock