--[[

	ServiceTemplate.luau
	Service

	Contributors:
	* YOUR NAME - YOUR ROLE since YYYY-MM-DD

	Created: YYYY-MM-DD
	Last Modified: YYYY-MM-DD

	Version: 1.2.3
	Increment the first number for breaking changes.
	Increment the second for new backwards-compatible functionality.
	Increment the third for bug fixes.

	Licence: MPL-2.0

	Description:
	Describe the service here.
	Keep this short and specific to the module's purpose.

	Dependencies:
	* Add any required modules, services, or libraries here.

]]

-- Argument documentation can have three tags for guidance.
-- [MUST] indicates the argument has to follow this rule or something evil will happen.
-- [SHOULD] indicates the argument ought to follow this rule or the program may not work as intended.
-- [MAY] indicates the argument can be controlled to produce different results.



local Service = {}

-- Preamble
-- This is where module imports, citations and declarations go.



-- Types
-- This is where types go.



-- Constants
-- This is where constant values go.



-- Variables
-- This is where shared mutable state goes.



-- Functions
-- This is where functions that calculate and return a value go.



-- Procedures
-- This is where functions designed to do something outside of computing and returning a value go.



-- Lifecycle
-- This is what the service should do nearly autonomously.

--[[
Sets up the service.

Inputs:
* (none)

Actions:
Sets up the service's passive elements.

Returns:
* (none)
]]
function Service:Init()

end

--[[
Begins the active operation of the service.

Inputs:
* (none)

Actions:
Starts the service's active elements.

Returns:
* (none)
]]
function Service:Start()

end



-- Termination
return Service