--[[

	ServiceTemplate.luau
	Service

	Contributors:
	* Irene "lacelit684" - Lead Developer since 2026-06-27
	State role, add and remove as needed.
	
	Created: 2026-06-27
	Last Modified: 2026-06-27
	Keep these up to date or your records will suffer your incompetence.

	Version: 1.2.3
	Increment the first number for breaking changes.
	Increment the second for new backwards-compatible functionality.
	Increment the third for bug fixes.

	Licence: MPL-2.0

	Description:
	Describe the service here.
	Keep this short and specific to the module's purpose.

	Dependencies:
	Add any required modules, services, or libraries here.

]]

local Service = {}

-- Preamble
-- This is where module imports, citations and declarations go.

-- Types
-- This is where types go.

-- Constants
-- This is where constant values go.

-- Variables
-- This is where shared mutable state goes.

-- Functions
-- This is where functions that calculate and return a value go.

-- Procedures
-- This is where functions designed to do something outside of computing and returning a value go.

-- Lifecycle

function Service:Init()

end

function Service:Start()

end



-- Termination
return Service