--[[

	ControllerTemplate.luau
	Runtime Controller
	
	Contributors:
	* YOUR NAME - YOUR ROLE since YYYY-MM-DD
	
	Created: YYYY-MM-DD
	Last Modified: YYYY-MM-DD
	
	Version: 1.2.3
	
	Licence: LICENCE
	
	Description:
	REPLACE
	
	Citations:
	[1] AS NEEDED

	Dependencies:
	AS NEEDED
	
]]



-- Preamble

local Controller = {}



-- Types



-- Constants



-- Variables



-- Functions



-- Procedures



-- Lifecycle



-- Termination

return Controller