--[[

	ServiceTemplate.luau
	Utility Library
	
	Contributors:
	* YOUR NAME - YOUR ROLE since YYYY-MM-DD
	
	Created: YYYY-MM-DD
	Last Modified: YYYY-MM-DD
	
	Version: 1.2.3
	
	Licence: LICENCE
	
	Description:
	REPLACE

	Dependencies:
	AS NEEDED
	
]]



-- Preamble

local Service = {}
Service.__index = Service



-- Types

type ClassData = {

}

export type Service = typeof(setmetatable({} :: ClassData, Service))



-- Types



-- Constants



-- Variables



-- Functions



-- Procedures



-- Termination

return Service