--[[

	ServiceTemplate.luau
	Service
	
	Contributors:
	* YOUR NAME - YOUR ROLE since YYYY-MM-DD
	
	Created: YYYY-MM-DD
	Last Modified: YYYY-MM-DD
	
	Version: 1.2.3
	
	Licence: LICENCE
	
	Description:
	REPLACE

	Dependencies:
	AS NEEDED
	
]]



-- Preamble

local Service = {}



-- Types



-- Constants



-- Variables



-- Functions



-- Procedures



-- Lifecycle



-- Termination

return Service